services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: atm_db
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: atm_user
      DB_PASSWORD: atm_password
      DB_NAME: atm_db
    volumes:
      - ./backend:/app
      - /app/vendor
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
